SELECT MIN(DOCTOR), MIN(PROFESSOR), MIN(SINGER), MIN(ACTOR)
FROM
    (SELECT ROW_NUMBER() OVER(PARTITION BY DOCTOR,ACTOR,SINGER,PROFESSOR 
     ORDER BY NAME ASC) AS ROWNUM, 
    CASE WHEN DOCTOR = 1 THEN NAME ELSE NULL END AS DOCTOR,
    CASE WHEN ACTOR = 1 THEN NAME ELSE NULL END AS ACTOR,
    CASE WHEN SINGER = 1 THEN NAME ELSE NULL END AS SINGER,
    CASE WHEN PROFESSOR = 1 THEN NAME ELSE NULL END AS PROFESSOR
FROM OCCUPATIONS
PIVOT
    ( COUNT(OCCUPATION)
      FOR OCCUPATION IN (DOCTOR, ACTOR, SINGER, PROFESSOR)) AS P) TEMP
GROUP BY ROWNUM;